### ISSUE TITLE
Remontée de la consommation par radiateur

### ISSUE THREAD

**Issue by Najihel** [noiwid/tiko_heating_api#13]
Bonjour,

Serait-il possible d'ajouter la partie consommation pour chaque radiateur afin de les intégrer dans le Dashboard énergie ?

Consommation globale : https://particuliers-tiko.fr/api/v3/properties/220001641/consumption_summary/

Par exemple :

```json
{
	"status": "ok",
	"response": {
		"today_total_wh": 1124,
		"yesterday_total_same_time_wh": 5799,
		"last_month_total_wh": 7374,
		"this_month_total_wh": 101868,
		"last_month_total_same_day_wh": 771
	}
}
```

Consommation par radiateur : https://particuliers-tiko.fr/api/v3/properties/220001641/status/

Example :

```json
{
	"status": "ok",
	"response": [
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 1,
			"timestamp": 1700149048535,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149048371,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149048816,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149049164,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149048976,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149048359,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149048000,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "DEH",
			"consumption": 0,
			"timestamp": 1700149049128,
			"connected": true,
			"relay_state": 0
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 19.9,
			"humidity": 75,
			"timestamp": 1700148946352,
			"rssi": -59,
			"batteryLevel": 97,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 18.7,
			"humidity": 74,
			"timestamp": 1700148836548,
			"rssi": -39,
			"batteryLevel": 92,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 18.5,
			"humidity": 76,
			"timestamp": 1700148880886,
			"rssi": -70,
			"batteryLevel": 96,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 17.9,
			"humidity": 79,
			"timestamp": 1700148910464,
			"rssi": -60,
			"batteryLevel": 96,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 18.2,
			"humidity": 86,
			"timestamp": 1700148797515,
			"rssi": -66,
			"batteryLevel": 92,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 18.5,
			"humidity": 74,
			"timestamp": 1700149039284,
			"rssi": -64,
			"batteryLevel": 93,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 17,
			"humidity": 76,
			"timestamp": 1700149028772,
			"rssi": -71,
			"batteryLevel": 93,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		},
		{
			"mac": "FFFF<snip>",
			"code": "SEN",
			"temperature": 18.3,
			"humidity": 80,
			"timestamp": 1700148762802,
			"rssi": -67,
			"batteryLevel": 92,
			"leftButtonPress": false,
			"rightButtonPress": false,
			"connected": true
		}
	]
}
```

Cordialement

**Comment by noiwid** [comment]
Hello,
Je viens de creuser un peu le sujet, la donnée qui remonte dans le champ consumption sur https://particuliers-tiko.fr/api/v3/properties/220001641/status/ est difficilement exploitable, c'est la consommation d'un radiateur à l'instant T en W, et ne peut donc pas être utilisée pour alimenter le dashboard Energy de H.A, ni pour faire aucun calculs...  

Qu'en penses-tu?

**Comment by Najihel** [comment]
Bonjour,

La consommation à l'instant T en Watt peut aller dans un sensor, ensuite il est possible d'utiliser ce sensor dans un autre sensor pour le "convertir" en Wh ou kWh pour obtenir la consommation détaillée de chaque radiateur.

Exemple pour un onduleur


```yaml
template:
  - sensor:
    - name: "Grenier-Onduleur Power"
      unique_id: sensor.grenier_onduleur_power
      state_class: measurement
      device_class: power  
      unit_of_measurement: "W"
      state: "{{ states('sensor.grenier_onduleur_load')|float * 0.01 * 480|round(2) }}"
    - name: "Grenier-Onduleur Energy"
      unique_id: sensor.grenier_onduleur_energy
      unit_of_measurement: "Wh"
      state: "{{ states('sensor.grenier_onduleur_watt') }}"
      state_class: "total_increasing"
      device_class: "energy"
sensor:
  - platform: integration
    name: "Grenier-Onduleur Watt"
    unique_id: sensor.grenier_onduleur_watt
    source: sensor.grenier_onduleur_power
    round: 2
    unit_prefix: k
```
