### ISSUE TITLE
YAML config is invalid

### ISSUE THREAD

**Issue by Najihel** [noiwid/tiko_heating_api#6]
Hello,

The YAML Config is invalid

```
Package tiko setup failed. Component tiko Integration 'tiko' not found.
```

Because the generated YAML config file mustn't begin with `tiko:` tree

Just comment the first line fix this problem.

Regards,

**Comment by noiwid** [comment]
Hi, 
I'm not sure to understand your feedback. If you include TIKO as a package following my instructions (means in /config/packages/tiko/ folder), and you put inside a tiko.yaml config file, from what I know you need to start your yaml by **tiko:** to load the package.

Did you get it working with another way?

**Comment by Najihel** [comment]
Hello @noiwid 

A snip of my `/config/configuration.yaml`

```yaml
# Packages
homeassistant:
  packages:
    google: !include packages/google/configuration.yaml
    telegram: !include packages/telegram/configuration.yaml
    lgtv: !include packages/lgtv/configuration.yaml
    checkupdates: !include packages/check-updates/configuration.yaml
    nighttime: !include packages/nighttime/configuration.yaml
    freeboxalarm: !include packages/freebox-alarm/configuration.yaml
    onduleurs: !include packages/onduleurs/configuration.yaml
    tiko: !include packages/tiko/configuration.yaml
```

With the `tiko:` level on YAML, the check config made a warning :

```
Package tiko setup failed. Component tiko Integration 'tiko' not found.
```

I tried yo rename `packages/tiko/configuration.yaml` to `packages/tiko/tiko.yaml` like your documentation but the issue is still present.
